version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - prisma-mysql

  prisma-mysql:
    image: mysql
    container_name: prisma-mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    name: nest-db
