version: '3.8'
services:
  prisma-mysql:
    image: mysql
    container_name: prisma-mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    name: nest-db
